
BEGIN;
TRUNCATE TABLE engine_wal RESTART IDENTITY CASCADE;
TRUNCATE TABLE swap_matches RESTART IDENTITY CASCADE;
TRUNCATE TABLE swap_listings RESTART IDENTITY CASCADE;
TRUNCATE TABLE margin_holds RESTART IDENTITY CASCADE;
TRUNCATE TABLE trades RESTART IDENTITY CASCADE;
TRUNCATE TABLE listings RESTART IDENTITY CASCADE;
TRUNCATE TABLE transactions RESTART IDENTITY CASCADE;
TRUNCATE TABLE accounts RESTART IDENTITY CASCADE;
DELETE FROM users WHERE username <> 'admin';
SELECT 'users' AS t, COUNT(*) FROM users;
SELECT 'listings' AS t, COUNT(*) FROM listings;
SELECT 'trades' AS t, COUNT(*) FROM trades;
ROLLBACK;
